### PR TITLE
no_jira update to new rubocop names

### PR DESCRIPTION
**Pull request by yinonrousso**

### CODE REVIEW

**Comment by alecjacobs5401** [comment]
I was just going to double check that. @yinonrousso what version of rubocop were you running with?

**Comment by yinonrousso** [comment]
I was running version (0.89.1.) Are we on an older version? @alecjacobs5401

**Comment by alecjacobs5401** [comment]
@yinonrousso Yeah, you can see where [web has it pinned to 0.74.0](https://github.com/Invoca/web/blob/561f6c4f77c81a3bd431ec286d7c0e1af933198d/Gemfile#L406)

If you were running into this while working in web, you can use `bundle exec rubocop` to ensure you use the correct version.

if you're running with it outside of web, we should pin those versions to match.

For what its worth, we have [Hound to configure to run rubocop 0.72.0](https://github.com/Invoca/style-guide/blob/master/.hound.yml#L2)

**Comment by yinonrousso** [comment]
@alecjacobs5401 I was running it in [pnapi_models](https://github.com/Invoca/pnapi_models/blob/master/Gemfile#L46). It was running at `0.76.0` before I ran a `bundle update`. I'll go ahead and lock it down in the Gemfile and close out this pr. Thank you!

**Pull request closed without merging**
